server:
  port: 8081

spring:
  application:
    name: booking-service
  r2dbc:
    password: ${DB_PASSWORD}
    url: r2dbc:postgresql://${DB_HOST:localhost}:5432/${DB_BOOKING_DATABASE}?stringtype=unspecified
    username: ${DB_USERNAME}
    driver-class-name: org.postgresql.Driver
  datasource:
    password: ${DB_PASSWORD}
    url: jdbc:postgresql://${DB_HOST:localhost}:5432/${DB_BOOKING_DATABASE}?stringtype=unspecified
    username: ${DB_USERNAME}
    driver-class-name: org.postgresql.Driver
  liquibase:
    changeLog: classpath:db/changelog/changelog-master.yaml
    enabled: true
    password: ${DB_PASSWORD}
    url: jdbc:postgresql://${DB_HOST:localhost}:5432/${DB_BOOKING_DATABASE}?stringtype=unspecified
    user: ${DB_USERNAME}
    driver-class-name: org.postgresql.Driver
  jackson:
    property-naming-strategy: SNAKE_CASE
  mvc:
    problemdetails:
      enabled: true
  webflux:
    problemdetails:
      enabled: true

eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA_HOST:localhost}:8071/eureka
      register-with-eureka: true
      fetch-registry: true
  instance:
    prefer-ip-address: true

springdoc:
  disable-swagger-default-url: true
  api-docs:
    path: /api-docs

resilience4j:
  circuitbreaker:
    configs:
      default:
        registerHealthIndicator: true
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
    instances:
      serviceX:
        baseConfig: default
