server:
  port: 8073

spring:
  application:
    name: gateway-server
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/user-service/**
          filters:
            - name: CircuitBreaker
              args:
                name: userServiceCB
                fallbackUri: forward:/fallback/user-service
        - id: booking-service
          uri: lb://booking-service
          predicates:
            - Path=/booking-service/**
          filters:
            - name: CircuitBreaker
              args:
                name: bookingServiceCB
                fallbackUri: forward:/fallback/booking-service
        - id: user-office
          uri: lb://office-service
          predicates:
            - Path=/office-service/**
          filters:
            - name: CircuitBreaker
              args:
                name: officeServiceCB
                fallbackUri: forward:/fallback/office-service

resilience4j:
  circuitbreaker:
    configs:
      default:
        registerHealthIndicator: true
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 20
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
        permittedNumberOfCallsInHalfOpenState: 5
        minimumNumberOfCalls: 10
        automaticTransitionFromOpenToHalfOpenEnabled: true
    instances:
      userServiceCB:
        baseConfig: default
      officeServiceCB:
        baseConfig: default
      bookingServiceCB:
        baseConfig: default
  timelimiter:
    configs:
      default:
        timeoutDuration: 3s
        cancelRunningFuture: true
    instances:
      userServiceCB:
        baseConfig: default
      officeServiceCB:
        baseConfig: default
      bookingServiceCB:
        baseConfig: default

eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA_HOST:localhost}:8071/eureka
      register-with-eureka: true
      fetch-registry: true
    instance:
      prefer-ip-address: true

springdoc:
  swagger-ui:
    path: /swagger-ui
    config-url: /v3/api-docs/swagger-config
    urls:
      - name: user-service
        url: /user-service/api-docs
      - name: office-service
        url: /office-service/api-docs
      - name: booking-service
        url: /booking-service/api-docs
      - name: gateway-server
        url: /api-docs
  api-docs:
    path: /api-docs
    enabled: true
