server:
  port: 8073

spring:
  application:
    name: gateway-server
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: service-x
          uri: lb://service-x
          predicates:
            - Path=/service-x/**
          filters:
            - name: CircuitBreaker
              args:
                name: serviceXCB
                fallbackUri: forward:/fallback/service-x
        - id: service-y
          uri: lb://service-y
          predicates:
            - Path=/service-y/**
          filters:
            - name: CircuitBreaker
              args:
                name: serviceYCB
                fallbackUri: forward:/fallback/service-y

resilience4j:
  circuitbreaker:
    configs:
      default:
        registerHealthIndicator: true
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 20
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
        permittedNumberOfCallsInHalfOpenState: 5
        minimumNumberOfCalls: 10
        automaticTransitionFromOpenToHalfOpenEnabled: true
    instances:
      serviceXCB:
        baseConfig: default
      serviceYCB:
        baseConfig: default
  timelimiter:
    configs:
      default:
        timeoutDuration: 3s
        cancelRunningFuture: true
    instances:
      serviceXCB:
        baseConfig: default
      serviceYCB:
        baseConfig: default

eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA_HOST:localhost}:8071/eureka
      register-with-eureka: true
      fetch-registry: true
    instance:
      prefer-ip-address: true

springdoc:
  swagger-ui:
    path: /swagger-ui
    config-url: /api-docs/swagger-config
    urls:
      - name: user-service
        url: /user-service/api-docs
      - name: office-service
        url: /office-service/api-docs
      - name: booking-service
        url: /booking-service/api-docs
  api-docs:
    enabled: true
