spring:
  application:
    name: service-x
  datasource:
    password: ${DB_PASSWORD}
    url: jdbc:postgresql://${DB_HOST:localhost}:5432/${DB_DATABASE}?stringtype=unspecified
    username: ${DB_USERNAME}
  liquibase:
    changeLog: classpath:db/changelog/changelog-master.yaml
    enabled: false
server:
  port: 8081
eureka:
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_HOST:localhost}:8071/eureka
