server:
  port: 8082

spring:
  application:
    name: service-y
  datasource:
    password: ${DB_PASSWORD}
    url: jdbc:postgresql://${DB_HOST:localhost}:5432/${DB_DATABASE}?stringtype=unspecified
    username: ${DB_USERNAME}
    driver-class-name: org.postgresql.Driver
  liquibase:
    changeLog: classpath:db/changelog/changelog-master.yaml
    enabled: false
  jpa:
    hibernate:
      ddl-auto: validate
  jackson:
    property-naming-strategy: SNAKE_CASE

eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA_HOST:localhost}:8071/eureka
      register-with-eureka: true
      fetch-registry: true
  instance:
    prefer-ip-address: true

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui
